CREATE TABLE ROLE
(
	ID_ROLE INT(10) NOT NULL AUTO_INCREMENT,
    ROLE VARCHAR(45) NOT NULL,
    PRIMARY KEY (ID_ROLE)
);

CREATE TABLE USER
(
	ID_USER INT(10) NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(45) NOT NULL,
    PASSWORD VARCHAR(45) NOT NULL,
    NAME VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(45) DEFAULT NULL,
    PHONE INT(10) DEFAULT NULL,
    STATUS INT(3) NOT NULL DEFAULT '0',
    PRIMARY KEY(ID_USER)
);

CREATE TABLE USER_ROLE
(
	ID_USER INT(10) NOT NULL,
    ID_ROLE INT(10) NOT NULL,
    PRIMARY KEY(ID_USER, ID_ROLE), 
	CONSTRAINT `FK_ROLE` FOREIGN KEY (ID_ROLE) REFERENCES ROLE(ID_ROLE),
    CONSTRAINT `FK_USER` FOREIGN KEY (ID_USER) REFERENCES USER(ID_USER)
);

CREATE TABLE PROVINCE
(
	ID_PROVINCE VARCHAR(10) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    PRIMARY KEY(ID_PROVINCE)
);

CREATE TABLE TOUR
(
	ID_TOUR VARCHAR(10) NOT NULL,
    NAME VARCHAR(45) NOT NULL,
    IMAGE VARCHAR(100) NOT NULL,
    PRIMARY KEY(ID_TOUR)
);

CREATE TABLE TOUR_INFORMATION
(
	ID_TOUR VARCHAR(10) NOT NULL,
    DETAIL LONGTEXT,
    IMAGE_FULL VARCHAR(100) NOT NULL,
    PRICE DOUBLE NOT NULL DEFAULT '0',
    ID_PROVINCE VARCHAR(10),
    STATUS INT(2) NOT NULL DEFAULT '0',
    PRIMARY KEY(ID_TOUR),
    CONSTRAINT `FK_TOUR_TOURINFO` FOREIGN KEY (ID_TOUR) REFERENCES TOUR(ID_TOUR),
	CONSTRAINT `FK_TOUR_PROVINCE` FOREIGN KEY (ID_PROVINCE) REFERENCES PROVINCE(ID_PROVINCE)
);
CREATE TABLE COMMENT 
(
	ID_CMT VARCHAR(10) NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    CONTENT LONGTEXT,
    ID_TOUR VARCHAR(10) NOT NULL,
	PRIMARY KEY(ID_CMT),
	CONSTRAINT `FK_COMMENT_TOURINFO` FOREIGN KEY (ID_TOUR) REFERENCES TOUR_INFORMATION(ID_TOUR)
);

CREATE TABLE ORDER_TOUR
(
	ID_ORDER VARCHAR(10) NOT NULL,
    ID_TOUR VARCHAR(10) NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    PHONE INT(10) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    PASSENGERS INT(2) NOT NULL,
    DECRIPTION LONGTEXT,
    PRIMARY KEY(ID_ORDER),
    CONSTRAINT `FK_ORDER_TOURINFO` FOREIGN KEY (ID_TOUR) REFERENCES TOUR(ID_TOUR)
)